apiVersion: v1
kind: Service
metadata:
  name: health-service
  labels:
    app: health
spec:
  selector:
    app: health
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP