spring:
  application:
    name: management

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/iroom_management?serverTimezone=Asia/Seoul
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        order_insert: true
        order_update: true
        show_sql: true
        format_sql: true
        jdbc:
          batch_size: 1000

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: management-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"





logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace  #sql 사용시 파라미터를 로그로 남긴다