name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./admin/pom.xml
          mvn clean package -f ./dashboard/pom.xml
          mvn clean package -f ./worker/pom.xml
          mvn clean package -f ./alarm/pom.xml
          mvn clean package -f ./management/pom.xml
          mvn clean package -f ./risk/pom.xml
          mvn clean package -f ./idle/pom.xml
          mvn clean package -f ./health/pom.xml
          mvn clean package -f ./eqipment/pom.xml
          mvn clean package -f ./sensor/pom.xml

      - name: Docker Build and push for Admin
        uses: docker/build-push-action@v4
        with:
          context: ./admin
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/admin:latest
            ghcr.io/${{ github.repository }}/admin:${{ github.ref_name }}
            
      - name: Docker Build and push for Dashboard
        uses: docker/build-push-action@v4
        with:
          context: ./dashboard
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/dashboard:latest
            ghcr.io/${{ github.repository }}/dashboard:${{ github.ref_name }}
            
      - name: Docker Build and push for Worker
        uses: docker/build-push-action@v4
        with:
          context: ./worker
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/worker:latest
            ghcr.io/${{ github.repository }}/worker:${{ github.ref_name }}
            
      - name: Docker Build and push for Alarm
        uses: docker/build-push-action@v4
        with:
          context: ./alarm
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/alarm:latest
            ghcr.io/${{ github.repository }}/alarm:${{ github.ref_name }}
            
      - name: Docker Build and push for Management
        uses: docker/build-push-action@v4
        with:
          context: ./management
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/management:latest
            ghcr.io/${{ github.repository }}/management:${{ github.ref_name }}
            
      - name: Docker Build and push for Risk
        uses: docker/build-push-action@v4
        with:
          context: ./risk
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/risk:latest
            ghcr.io/${{ github.repository }}/risk:${{ github.ref_name }}
            
      - name: Docker Build and push for Idle
        uses: docker/build-push-action@v4
        with:
          context: ./idle
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/idle:latest
            ghcr.io/${{ github.repository }}/idle:${{ github.ref_name }}
            
      - name: Docker Build and push for Health
        uses: docker/build-push-action@v4
        with:
          context: ./health
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/health:latest
            ghcr.io/${{ github.repository }}/health:${{ github.ref_name }}
            
      - name: Docker Build and push for Eqipment
        uses: docker/build-push-action@v4
        with:
          context: ./eqipment
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/eqipment:latest
            ghcr.io/${{ github.repository }}/eqipment:${{ github.ref_name }}
            
      - name: Docker Build and push for Sensor
        uses: docker/build-push-action@v4
        with:
          context: ./sensor
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/sensor:latest
            ghcr.io/${{ github.repository }}/sensor:${{ github.ref_name }}
            
