apiVersion: v1
kind: Service
metadata:
  name: alarm-service
  labels:
    app: alarm
spec:
  selector:
    app: alarm
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8084
  type: ClusterIP