apiVersion: apps/v1
kind: Deployment
metadata:
  name: risk
  labels:
    app: risk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: risk
  template:
    metadata:
      labels:
        app: risk
    spec:
      containers:
        - name: risk
          image: "username/risk:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
