server:
  port: 8084

spring:
  application:
    name: alarm

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/iroom_alarm?serverTimezone=Asia/Seoul
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        order_insert: true
        order_update: true
        show_sql: true
        format_sql: true
        jdbc:
          batch_size: 1000

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: alarm-service
      auto-offset-reset: earliest

  cloud:
    stream:
      bindings:
        event-in:
          destination: iroom
          contentType: application/json
        event-out:
          destination: iroom
          contentType: application/json

---

spring:
  config:
    activate:
      on-profile: default

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug

---

spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql:3306/iroom_alarm?serverTimezone=Asia/Seoul
  kafka:
    bootstrap-servers: kafka:9093

---

spring:
  config:
    activate:
      on-profile: k8s
  datasource:
    url: jdbc:mysql://i-room-mysql/iroom_alarm?serverTimezone=Asia/Seoul

  kafka:
    bootstrap-servers: i-room-kafka:9092