apiVersion: v1
kind: Service
metadata:
  name: management-service
  labels:
    app: management
spec:
  selector:
    app: management
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: ClusterIP